/**
 * OPTIMIERT: Synonym-Mappings in separater Datei für bessere Performance
 * Diese Datei wird nur einmal geladen und kann gecached werden
 */

// Kategorie-Keyword-Mapping (spezifisch, um Verwechslungen zu vermeiden)
export const categoryKeywords: Record<string, string[]> = {
  'auto-motorrad': [
    'fahrzeug',
    'pkw',
    'wagen',
    'bmw',
    'mercedes',
    'audi',
    'vw',
    'volkswagen',
    'porsche',
    'tesla',
    'ferrari',
    'lamborghini',
    'mclaren',
    'motorrad',
    'motorcycle',
    'bike',
    'ducati',
    'yamaha',
    'kawasaki',
    'honda',
    'suzuki',
    'e-tron',
    'amg',
    'series',
    'klasse',
  ],
  'uhren-schmuck': [
    'rolex',
    'omega',
    'submariner',
    'speedmaster',
    'datejust',
    'daytona',
    'seamaster',
    'aquanaut',
    'nautilus',
    'hublot',
    'breitling',
    'patek',
    'audemars',
    'cartier',
    'iwc',
    'panerai',
    'tag heuer',
    'tudor',
    'longines',
    'tissot',
    'sinn',
    'steinhart',
    'armbanduhr',
    'chronograph',
    'taucheruhr',
  ],
  'computer-netzwerk': [
    'laptop',
    'notebook',
    'macbook',
    'thinkpad',
    'computer',
    'pc',
    'desktop',
    'tablet',
    'ipad',
    'monitor',
    'bildschirm',
    'drucker',
    'printer',
    'scanner',
    'tastatur',
    'keyboard',
    'maus',
    'mouse',
    'dell',
    'hp',
    'lenovo',
    'asus',
    'acer',
    'msi',
  ],
  'handy-telefon': [
    'handy',
    'smartphone',
    'iphone',
    'galaxy',
    'pixel',
    'telefon',
    'mobile',
    'samsung',
    'huawei',
    'xiaomi',
    'oppo',
    'oneplus',
    'sony xperia',
  ],
  'foto-optik': [
    'kamera',
    'camera',
    'spiegelreflex',
    'objektiv',
    'lens',
    'canon',
    'nikon',
    'sony alpha',
    'fuji',
    'fujifilm',
    'leica',
    'panasonic',
    'olympus',
    'pentax',
    'eos',
    'lumix',
    'gopro',
    'drohne',
    'drone',
    'dji',
  ],
  sport: [
    'fahrrad',
    'velo',
    'rennrad',
    'mountainbike',
    'e-bike',
    'fitness',
    'ski',
    'snowboard',
    'camping',
    'outdoor',
    'trek',
    'specialized',
    'canyon',
    'scott',
    'cube',
    'giant',
    'garmin',
  ],
  'kleidung-accessoires': [
    'jacke',
    'jacket',
    'hose',
    'pants',
    'shirt',
    'hemd',
    'pullover',
    'schuhe',
    'shoes',
    'sneaker',
    'tasche',
    'bag',
    'rucksack',
    'nike',
    'adidas',
    'gucci',
    'prada',
    'louis vuitton',
    'balenciaga',
    'moncler',
  ],
  'haushalt-wohnen': [
    'möbel',
    'furniture',
    'sofa',
    'couch',
    'tisch',
    'table',
    'stuhl',
    'chair',
    'lampe',
    'lamp',
    'teppich',
    'carpet',
    'küche',
    'kitchen',
    'staubsauger',
    'vacuum',
    'dyson',
    'miele',
    'kaffeemaschine',
    'nespresso',
    'jura',
  ],
  'handwerk-garten': [
    'werkzeug',
    'bohrmaschine',
    'säge',
    'hammer',
    'schraubenzieher',
    'rasenmäher',
    'garten',
    'grill',
    'weber',
    'bosch professional',
    'makita',
    'dewalt',
    'stihl',
    'husqvarna',
  ],
  'games-konsolen': [
    'playstation',
    'xbox',
    'nintendo',
    'switch',
    'ps5',
    'ps4',
    'konsole',
    'console',
    'game',
    'gaming',
  ],
  'musik-instrumente': [
    'gitarre',
    'guitar',
    'piano',
    'klavier',
    'keyboard',
    'schlagzeug',
    'drums',
    'yamaha',
    'fender',
    'gibson',
    'roland',
  ],
}

// Umfangreiches Synonym-Mapping für intelligente Suche
// Unterstützt: Plural/Singular, Umlaute, Mehrsprachigkeit, Tippfehler, Markennamen
export const searchSynonyms: Record<string, string[]> = {
  // SCHUHE & BEKLEIDUNG
  schuhe: [
    'sneaker',
    'shoes',
    'sneakers',
    'turnschuhe',
    'sportschuhe',
    'laufschuhe',
    'sportschuh',
    'sportsschuhe',
    'wanderschuhe',
    'trekking',
    'stiefel',
    'boots',
    'sandalen',
    'sandals',
    'pumps',
    'heels',
  ],
  sneaker: ['schuhe', 'shoes', 'sneakers', 'turnschuhe', 'sportschuhe', 'laufschuhe'],
  shoes: ['schuhe', 'sneaker', 'sneakers', 'turnschuhe', 'sportschuhe'],
  jacke: ['jacket', 'jacken', 'jackets', 'mantel', 'coat', 'mäntel', 'coats', 'parka', 'parkas'],
  hose: ['pants', 'hosen', 'trousers', 'jeans', 'jean', 'chino', 'chinos', 'cargo', 'cargohose'],
  shirt: ['hemd', 'hemden', 'shirts', 't-shirt', 'tshirt', 't-shirts', 'tshirts', 'polo', 'poloshirt'],
  pullover: ['sweater', 'sweaters', 'pullis', 'pulli', 'hoodie', 'hoodies', 'kapuzenpullover'],

  // UHREN & SCHMUCK
  uhr: [
    'watch',
    'armbanduhr',
    'wristwatch',
    'zeitmesser',
    'uhren',
    'watches',
    'wristwatches',
    'chronograph',
    'chronographen',
    'taucheruhr',
    'divewatch',
    'fliegeruhr',
    'pilotwatch',
  ],
  watch: ['uhr', 'armbanduhr', 'wristwatch', 'uhren', 'watches'],
  armbanduhr: ['uhr', 'watch', 'wristwatch', 'armbanduhren', 'watches'],
  schmuck: ['jewelry', 'jewellery', 'bijoux', 'ring', 'rings', 'ringe', 'kette', 'ketten', 'necklace'],
  ring: ['rings', 'ringe', 'verlobungsring', 'engagementring', 'ehering', 'weddingring', 'trauring'],
  kette: ['ketten', 'necklace', 'necklaces', 'halskette', 'halsketten', 'chain', 'chains'],

  // AUTO & MOTORRAD
  auto: ['fahrzeug', 'wagen', 'pkw', 'car', 'vehicle', 'fahrzeuge', 'wagen', 'cars', 'vehicles'],
  fahrzeug: ['auto', 'wagen', 'pkw', 'car', 'vehicle', 'automobil'],
  motorrad: ['motorcycle', 'bike', 'motorrad', 'motorräder', 'motorcycles', 'bikes', 'moped', 'mopeds'],
  motorcycle: ['motorrad', 'bike', 'motorräder', 'bikes', 'yamaha', 'honda', 'kawasaki', 'suzuki', 'ducati'],

  // COMPUTER & ELEKTRONIK
  laptop: ['notebook', 'computer', 'pc', 'laptops', 'notebooks', 'computers', 'pcs', 'macbook', 'macbooks', 'thinkpad'],
  notebook: ['laptop', 'computer', 'pc', 'laptops', 'notebooks', 'computers'],
  computer: ['pc', 'laptop', 'notebook', 'desktop', 'computers', 'pcs', 'laptops', 'notebooks', 'desktops'],
  pc: ['computer', 'laptop', 'notebook', 'desktop', 'rechner'],
  handy: ['smartphone', 'telefon', 'mobile', 'phone', 'handys', 'smartphones', 'telefone', 'mobiles', 'phones'],
  smartphone: ['handy', 'telefon', 'mobile', 'phone', 'iphone', 'galaxy', 'pixel'],

  // FOTO & OPTIK
  kamera: ['camera', 'kameras', 'cameras', 'fotokamera', 'photocamera', 'spiegelreflexkamera', 'dslr', 'systemkamera'],
  camera: ['kamera', 'kameras', 'cameras'],
  objektiv: ['lens', 'lenses', 'objektive', 'objektivs', 'glas', 'gläser', 'optik', 'optiken'],
  lens: ['objektiv', 'objektive', 'lenses'],
  drohne: ['drone', 'drohnen', 'drones', 'quadcopter', 'quadcopters', 'multicopter', 'multicopters', 'fpv'],
  drone: ['drohne', 'drohnen', 'drones'],

  // SPORT
  fahrrad: ['velo', 'bicycle', 'bike', 'fahrräder', 'velos', 'bicycles', 'bikes', 'rennrad', 'racingbike', 'mountainbike'],
  velo: ['fahrrad', 'bicycle', 'bike', 'fahrräder', 'bicycles', 'bikes'],
  ski: ['skis', 'skier', 'ski', 'skibretter', 'skiboard', 'skiboards', 'alpin', 'alpine', 'langlauf'],
  snowboard: ['snowboards', 'snowboard', 'board', 'boards', 'snowboardbrett', 'snowboardbretter'],
  fitness: ['fitnessgerät', 'fitnessgeräte', 'fitnessequipment', 'trainingsgerät', 'trainingsgeräte', 'trainingsequipment'],

  // HAUSHALT & WOHNEN
  möbel: ['furniture', 'möbel', 'furnitures', 'einrichtung', 'furnishings', 'sofa', 'sofas', 'couch', 'couches'],
  sofa: ['couch', 'sofas', 'couches', 'sitzgarnitur', 'sitzgarnituren', 'sitzgruppe', 'sitzgruppen'],
  couch: ['sofa', 'sofas', 'couches'],
  tisch: ['table', 'tables', 'tische', 'tischs'],
  stuhl: ['chair', 'chairs', 'stühle', 'stuhls'],
  lampe: ['lamp', 'lamps', 'lampen', 'leuchte', 'leuchten', 'light', 'lights', 'beleuchtung', 'lighting'],
  staubsauger: ['vacuum', 'vacuums', 'staubsauger', 'staubsaugers', 'sauger', 'saugers', 'saugroboter', 'robovac'],

  // HANDWERK & GARTEN
  werkzeug: ['tool', 'tools', 'werkzeuge', 'werkzeugs', 'werkzeugkasten', 'toolbox', 'toolboxes', 'bohrmaschine'],
  garten: ['garden', 'gardens', 'gärten', 'gartens', 'rasenmäher', 'lawnmower', 'lawnmowers', 'rasenmähers'],
  grill: ['grills', 'barbecue', 'barbecues', 'bbq', 'bbqs', 'grillgerät', 'grillgeräte', 'grillgeräts'],

  // GAMES & KONSOLEN
  playstation: ['ps', 'ps5', 'ps4', 'ps3', 'playstation', 'playstations', 'sony', 'konsole', 'console'],
  xbox: ['xbox', 'xboxs', 'xbox one', 'xbox series', 'xbox series x', 'xbox series s', 'microsoft', 'konsole'],
  nintendo: ['nintendo', 'nintendos', 'switch', 'switches', 'wii', 'wii u', '3ds', 'ds', 'gameboy'],

  // MUSIK & INSTRUMENTE
  gitarre: ['guitar', 'guitars', 'gitarren', 'gitarrens', 'akustikgitarre', 'acoustic guitar', 'elektrogitarre', 'electric guitar'],
  piano: ['klavier', 'klaviers', 'piano', 'pianos', 'flügel', 'grand piano', 'keyboard', 'keyboards'],
  klavier: ['piano', 'pianos', 'klavier', 'klaviers', 'flügel', 'grand piano'],
}



