/**
 * Generiert die duotone Alpen-/See-Silhouette für das SIC-Zertifikat-PDF.
 *
 * Aufruf: `npx tsx scripts/build-sic-cert-asset.ts`
 * Output:
 *   - public/sic/cert/backdrop-alps.png
 *   - src/lib/sic/cert/backdrop-asset.ts  (Base64 Data-URL für Serverless)
 */
import { mkdirSync, writeFileSync, readFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { execFileSync } from 'node:child_process'

const W = 900
const H = 420
const PNG_PATH = resolve(process.cwd(), 'public/sic/cert/backdrop-alps.png')
const TS_PATH = resolve(process.cwd(), 'src/lib/sic/cert/backdrop-asset.ts')

const PY = `
from PIL import Image, ImageDraw
import math

W, H = ${W}, ${H}
# Elfenbein-Basis, Navy-duotone Berge
IVORY = (251, 249, 243, 0)  # transparent start; we'll composite
NAVY = (15, 43, 94)
GOLD = (184, 145, 47)

img = Image.new('RGBA', (W, H), (251, 249, 243, 0))
draw = ImageDraw.Draw(img)

def mountain(points, alpha):
    fill = (*NAVY, alpha)
    draw.polygon(points, fill=fill)

# Far ridge (faint)
mountain([
    (0, H), (0, H*0.62),
    (80, H*0.48), (160, H*0.55), (240, H*0.38),
    (320, H*0.52), (420, H*0.28), (520, H*0.50),
    (600, H*0.35), (700, H*0.48), (780, H*0.30),
    (860, H*0.45), (W, H*0.40), (W, H)
], 28)

# Mid ridge
mountain([
    (0, H), (0, H*0.72),
    (100, H*0.58), (200, H*0.68), (300, H*0.50),
    (400, H*0.62), (500, H*0.42), (620, H*0.60),
    (720, H*0.48), (820, H*0.58), (W, H*0.52), (W, H)
], 42)

# Near ridge (stronger)
mountain([
    (0, H), (0, H*0.82),
    (60, H*0.70), (140, H*0.78), (220, H*0.64),
    (340, H*0.76), (460, H*0.58), (580, H*0.74),
    (700, H*0.62), (800, H*0.72), (W, H*0.68), (W, H)
], 55)

# Lake / mist band at bottom — soft gold wash
for y in range(int(H*0.78), H):
    t = (y - H*0.78) / (H*0.22)
    a = int(18 + t * 22)
    draw.line([(0, y), (W, y)], fill=(*GOLD, a))

# Soft vignette fade top
for y in range(0, int(H*0.35)):
    t = 1 - y / (H*0.35)
    a = int(t * 40)
    # erase toward transparent at top by reducing alpha of existing pixels
    pass

# Downscale for PDF size
out = img.resize((600, 280), Image.Resampling.LANCZOS)
out.save('${PNG_PATH}', 'PNG', optimize=True)
print('wrote', '${PNG_PATH}', 'bytes', __import__('os').path.getsize('${PNG_PATH}'))
`

function main() {
  mkdirSync(dirname(PNG_PATH), { recursive: true })
  execFileSync('python3', ['-c', PY], { stdio: 'inherit' })

  const buf = readFileSync(PNG_PATH)
  const b64 = buf.toString('base64')
  const dataUrl = `data:image/png;base64,${b64}`

  const ts = `/**
 * Auto-generated by scripts/build-sic-cert-asset.ts — do not edit by hand.
 * Duotone Alpen-/See-Silhouette als Data-URL für Serverless-PDF-Rendering.
 */
export const SIC_CERT_BACKDROP_DATA_URL =
  '${dataUrl}' as const
`
  writeFileSync(TS_PATH, ts)
  console.log(`wrote ${TS_PATH} (${Math.round(dataUrl.length / 1024)} KB data-url)`)
}

main()
