#!/bin/bash

# Exakte DNS-Konfiguration basierend auf Vercel Dashboard
# Diese Werte kommen direkt aus deinem Vercel Dashboard!

echo "🔧 Exakte DNS-Konfiguration für helvenda.ch"
echo "============================================"
echo ""
echo "📋 Diese Werte kommen direkt aus deinem Vercel Dashboard!"
echo ""

echo "1️⃣  Für helvenda.ch (Root Domain):"
echo "   ──────────────────────────────"
echo "   ⚠️  WICHTIG: Du musst die NAMESERVER bei deinem Domain-Registrar ändern!"
echo ""
echo "   Gehe zu deinem Domain-Registrar (nicht Vercel!)"
echo "   Ändere die Nameserver zu:"
echo ""
echo "   ┌─────────────────────────────────────────┐"
echo "   │ Nameserver 1: ns1.vercel-dns.com      │"
echo "   │ Nameserver 2: ns2.vercel-dns.com       │"
echo "   └─────────────────────────────────────────┘"
echo ""
echo "   ⚠️  Nach der Änderung kann es 1-48 Stunden dauern, bis die Nameserver propagiert sind!"
echo ""

echo "2️⃣  Für www.helvenda.ch:"
echo "   ──────────────────────────────"
echo "   ⚠️  WICHTIG: Dieser CNAME Record wird automatisch gesetzt,"
echo "   wenn du die Nameserver auf Vercel umstellst!"
echo ""
echo "   Falls du den CNAME manuell setzen musst:"
echo ""
echo "   ┌─────────────────────────────────────────────────────────────┐"
echo "   │ Typ:    CNAME Record                                        │"
echo "   │ Name:   www                                                 │"
echo "   │ Wert:   6ca6cf59469a5f6e.vercel-dns-016.com.               │"
echo "   │ TTL:    3600 (oder Auto)                                    │"
echo "   └─────────────────────────────────────────────────────────────┘"
echo ""

echo "3️⃣  Schritt-für-Schritt Anleitung:"
echo "   ──────────────────────────────"
echo ""
echo "   Schritt 1: Finde heraus, wer dein Domain-Registrar ist"
echo "   → Prüfe deine Domain-Registrierungs-E-Mails"
echo "   → Oder führe aus: whois helvenda.ch | grep -i registrar"
echo ""
echo "   Schritt 2: Logge dich bei deinem Domain-Registrar ein"
echo "   → Gehe zu DNS-Verwaltung / Nameserver-Einstellungen"
echo ""
echo "   Schritt 3: Ändere die Nameserver zu:"
echo "   → ns1.vercel-dns.com"
echo "   → ns2.vercel-dns.com"
echo "   → Speichere die Änderungen"
echo ""
echo "   Schritt 4: Warte auf Nameserver-Propagierung (1-48 Stunden)"
echo "   → Prüfe mit: dig NS helvenda.ch"
echo "   → Oder online: https://www.whatsmydns.net/#NS/helvenda.ch"
echo ""
echo "   Schritt 5: Gehe zurück zu Vercel"
echo "   → https://vercel.com/lucas-rodrigues-projects-1afdcdc5/helvenda/settings/domains"
echo "   → Klicke 'Refresh' bei helvenda.ch"
echo "   → Warte auf 'Valid Configuration' ✅"
echo ""

echo "4️⃣  Häufige Domain-Registrare:"
echo "   ──────────────────────────────"
echo "   → Hostpoint: https://www.hostpoint.ch"
echo "   → Switch: https://www.switch.ch"
echo "   → Infomaniak: https://www.infomaniak.com"
echo "   → GoDaddy: https://www.godaddy.com"
echo "   → Namecheap: https://www.namecheap.com"
echo ""

echo "5️⃣  Prüfe Nameserver-Status:"
echo "   ──────────────────────────────"
echo "   Führe aus: dig NS helvenda.ch"
echo "   Oder online: https://www.whatsmydns.net/#NS/helvenda.ch"
echo ""

