#!/bin/bash

# DNS Setup Script für helvenda.ch auf Vercel
# Dieses Script zeigt die benötigten DNS-Einträge an

echo "🔧 Helvenda.ch Domain DNS Setup"
echo "================================"
echo ""
echo "📋 Benötigte DNS-Einträge für deinen Domain-Provider:"
echo ""
echo "1️⃣  Für helvenda.ch (Root Domain):"
echo "   ┌─────────────────────────────────────────┐"
echo "   │ Typ:    A Record                        │"
echo "   │ Name:   @ (oder helvenda.ch)           │"
echo "   │ Wert:   76.76.21.21                    │"
echo "   │ TTL:    3600 (oder Auto)               │"
echo "   └─────────────────────────────────────────┘"
echo ""
echo "   ODER (wenn A Record nicht funktioniert):"
echo "   ┌─────────────────────────────────────────┐"
echo "   │ Typ:    CNAME Record                    │"
echo "   │ Name:   @ (oder helvenda.ch)           │"
echo "   │ Wert:   cname.vercel-dns.com           │"
echo "   │ TTL:    3600 (oder Auto)               │"
echo "   └─────────────────────────────────────────┘"
echo ""
echo "2️⃣  Für www.helvenda.ch:"
echo "   ┌─────────────────────────────────────────┐"
echo "   │ Typ:    CNAME Record                    │"
echo "   │ Name:   www                             │"
echo "   │ Wert:   cname.vercel-dns.com           │"
echo "   │ TTL:    3600 (oder Auto)               │"
echo "   └─────────────────────────────────────────┘"
echo ""
echo "📝 Nächste Schritte:"
echo "   1. Logge dich bei deinem Domain-Provider ein"
echo "   2. Gehe zu DNS-Verwaltung / DNS-Einstellungen"
echo "   3. Füge die oben genannten Einträge hinzu"
echo "   4. Speichere die Änderungen"
echo "   5. Warte 5-15 Minuten"
echo "   6. Prüfe DNS-Propagierung: https://www.whatsmydns.net/#A/helvenda.ch"
echo "   7. Gehe zu Vercel → Domains → Refresh"
echo ""
echo "⚠️  WICHTIG:"
echo "   - Die IP-Adresse kann variieren - prüfe in Vercel!"
echo "   - Wenn dein Provider '@' nicht unterstützt, verwende 'helvenda.ch'"
echo "   - DNS-Propagierung kann bis zu 48 Stunden dauern"
echo ""

